@startuml
'https://plantuml.com/class-diagram

package sae {

    class MapColors {
        + {static} getHashMapColor(img : BufferedImage) : Map<Integer, Integer>
        + {static} getTreeMapColor(img : BufferedImage) : Map<Integer, Integer>
    }

    note left{
        getHashMapColor retourne une HashMap
        getTreeMapColor retourne une TreeMap
    }
}

    package sae.solution_perso.solution2{
        class ColorsFromPaletteProvider {
            - imgColors : Map<Integer, Integer>
            - palette : Map<Integer, Boolean>
            + getColorsFromPalette(nb: int, res : int[]) : int[]
        }


        note left {
           L'attribut 'imgColors' est créée
           grâce à la méthode getHashMapColor
           de MapColors
        }
    }
}





@enduml