@startuml
'https://plantuml.com/class-diagram

package sae {

    class MapColors {
        + {static} getHashMapColors(img : BufferedImage) : Map<Integer, Integer>
        + {static} getTreeMapColors(img : BufferedImage) : Map<Integer, Integer>
    }

    note left{
        getHashMapColors retourne une HashMap
        getTreeMapColors retourne une TreeMap
    }
}

    package sae.solution_perso.solution3{
        class ColorsFromPaletteProvider {
            - imgColors : Map<Integer, Integer>
            - palette : Map<Integer, Boolean>
            + ColorsFromPaletteProvider(img : BufferedImage)
            + getColorsFromPalette(nb: int, res : int[]) : int[]
        }


        note left {
           L'attribut 'imgColors' est créée
           grâce à la méthode getHashMapColor
           de MapColors
        }
    }
}





@enduml