@startuml

package sae {

    class MapColors {
        + {static} getHashMapColors(img : BufferedImage) : Map<Integer, Integer>
        + {static} getTreeMapColors(img : BufferedImage) : Map<Integer, Integer>
    }

    note left{
        getHashMapColors retourne une HashMap
        getTreeMapColors retourne une TreeMap
    }
}

    package sae.solution_perso.solution4{
        class MaxColorsFromPartProvider {
            - colors : Map<Integer, Integer>
            + MaxColorsFromPartProvider(img : BufferedImage)
            + getMaxColorsFromParts(nb: int, res : int[]) : int[]
            + getColors() : Map<Integer, Integer>
        }


        note left {
           L'attribut 'colors' est créer
           grâce à la méthode getTreeMapColors
           de MapColors
        }
    }
}




@enduml